Repository GSG-FC03/fruit-salad-team-6, pull requests merged in 2021-06, with the labels that each got.

#2 create files and path structure
  html/add_to_basket.html
  html/home_screen.html
  index.html
  stylesheets/add_to_basket.css
  stylesheets/home_screen.css
  stylesheets/style.css
Labels: approved

#4 write read me file content -project team members
  README.md
Labels: approved

#8 create home screen layout and dsign
  html/home_screen.html
  images/Group.png
  images/combo 1.png
  images/combo 2.png
  images/heart.png
  images/ico2.png
  images/plus.png
  images/search.png
  stylesheets/home_screen.css
Labels: approved

#6 create wlecome page and style it using flex layout
  images/Ellipse.png
  images/fruit-basket.png
  index.html
  stylesheets/style.css
Labels: approved

#11 create add to basket screen
  html/add_to_basket.html
  images/Go back 3.png
  images/Line.png
  images/breakfast-quinoa-and-red-fruit-salad.png
  images/heart.png
  images/sub.png
  images/sum.png
  stylesheets/add_to_basket.css
Labels: awaiting-review, done

#15 added the live link, edited some typos and removed an unnecessary space
  README.md
Labels: done

#13 added hover on the button and a margin button
  stylesheets/style.css
Labels: done

#16 changes on home screen
  html/home_screen.html
  stylesheets/home_screen.css
Labels: done

#20 correct images addresses path
  html/add_to_basket.html
Labels: approved

#18 correct search icon address path
  html/home_screen.html
Labels: approved

#27 edit go back button
  html/add_to_basket.html
  stylesheets/add_to_basket.css
Labels: approved

#29 correct like icon
  html/home_screen.html
  images/like.png
Labels: done
